//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mitoSoft.Holidays {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mitoSoft.Holidays.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Saints&apos; Day.
        /// </summary>
        internal static string AllSaintsDay {
            get {
                return ResourceManager.GetString("AllSaintsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumption of Mary.
        /// </summary>
        internal static string AssumptionOfMary {
            get {
                return ResourceManager.GetString("AssumptionOfMary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing Day.
        /// </summary>
        internal static string BoxingDay {
            get {
                return ResourceManager.GetString("BoxingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Day.
        /// </summary>
        internal static string ChristmasDay {
            get {
                return ResourceManager.GetString("ChristmasDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Eve.
        /// </summary>
        internal static string ChristmasEve {
            get {
                return ResourceManager.GetString("ChristmasEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columbus Day.
        /// </summary>
        internal static string ColumbusDay {
            get {
                return ResourceManager.GetString("ColumbusDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Monday.
        /// </summary>
        internal static string EasterMonday {
            get {
                return ResourceManager.GetString("EasterMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Sunday.
        /// </summary>
        internal static string EasterSunday {
            get {
                return ResourceManager.GetString("EasterSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epiphany.
        /// </summary>
        internal static string Epiphany {
            get {
                return ResourceManager.GetString("Epiphany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feast of Corpus Christi.
        /// </summary>
        internal static string FeastOfCorpusChristi {
            get {
                return ResourceManager.GetString("FeastOfCorpusChristi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feast of the Ascension.
        /// </summary>
        internal static string FeastOfTheAscension {
            get {
                return ResourceManager.GetString("FeastOfTheAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washington&apos;s Birthday.
        /// </summary>
        internal static string GeorgeWashingtonsBirthday {
            get {
                return ResourceManager.GetString("GeorgeWashingtonsBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Unity Day.
        /// </summary>
        internal static string GermanUnityDay {
            get {
                return ResourceManager.GetString("GermanUnityDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Friday.
        /// </summary>
        internal static string GoodFriday {
            get {
                return ResourceManager.GetString("GoodFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigenous Peoples&apos; Day.
        /// </summary>
        internal static string IndigenousPeoplesDay {
            get {
                return ResourceManager.GetString("IndigenousPeoplesDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Women&apos;s Day.
        /// </summary>
        internal static string InternationalWomensDay {
            get {
                return ResourceManager.GetString("InternationalWomensDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juneteenth National Independence Day.
        /// </summary>
        internal static string JuneteenthNationalIndependenceDay {
            get {
                return ResourceManager.GetString("JuneteenthNationalIndependenceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labor day.
        /// </summary>
        internal static string LaborDay {
            get {
                return ResourceManager.GetString("LaborDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luther Reformation Day.
        /// </summary>
        internal static string LutherRefomationDay {
            get {
                return ResourceManager.GetString("LutherRefomationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martin Luther King Jr. Day.
        /// </summary>
        internal static string MartinLutherKingJrDay {
            get {
                return ResourceManager.GetString("MartinLutherKingJrDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maundy Thursday.
        /// </summary>
        internal static string MaundyThursday {
            get {
                return ResourceManager.GetString("MaundyThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s Day.
        /// </summary>
        internal static string NewYearsDay {
            get {
                return ResourceManager.GetString("NewYearsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s Eve.
        /// </summary>
        internal static string NewYearsEve {
            get {
                return ResourceManager.GetString("NewYearsEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentecost Sunday.
        /// </summary>
        internal static string PentecostSunday {
            get {
                return ResourceManager.GetString("PentecostSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving Day.
        /// </summary>
        internal static string ThanksgivingDay {
            get {
                return ResourceManager.GetString("ThanksgivingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independence Day.
        /// </summary>
        internal static string UnitedStatesIndependenceDay {
            get {
                return ResourceManager.GetString("UnitedStatesIndependenceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memorial Day.
        /// </summary>
        internal static string UnitedStatesMemorialDay {
            get {
                return ResourceManager.GetString("UnitedStatesMemorialDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterans Day.
        /// </summary>
        internal static string VeteransDay {
            get {
                return ResourceManager.GetString("VeteransDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whit Monday.
        /// </summary>
        internal static string WhitMonday {
            get {
                return ResourceManager.GetString("WhitMonday", resourceCulture);
            }
        }
    }
}
