//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mitoSoft.Holidays.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mitoSoft.Holidays.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Saints&apos; Day.
        /// </summary>
        internal static string allSaints {
            get {
                return ResourceManager.GetString("allSaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feast of the Ascension.
        /// </summary>
        internal static string ascensionOfChrist {
            get {
                return ResourceManager.GetString("ascensionOfChrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumption of Mary.
        /// </summary>
        internal static string assumptionDay {
            get {
                return ResourceManager.GetString("assumptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing Day.
        /// </summary>
        internal static string boxingDay {
            get {
                return ResourceManager.GetString("boxingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Day.
        /// </summary>
        internal static string christmasDay {
            get {
                return ResourceManager.GetString("christmasDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Eve.
        /// </summary>
        internal static string christmasEve {
            get {
                return ResourceManager.GetString("christmasEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feast of Corpus Christi.
        /// </summary>
        internal static string corpusChristi {
            get {
                return ResourceManager.GetString("corpusChristi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Sunday.
        /// </summary>
        internal static string easter {
            get {
                return ResourceManager.GetString("easter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Monday.
        /// </summary>
        internal static string easterMonday {
            get {
                return ResourceManager.GetString("easterMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epiphany.
        /// </summary>
        internal static string epiphany {
            get {
                return ResourceManager.GetString("epiphany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Unity Day.
        /// </summary>
        internal static string germanUnityDay {
            get {
                return ResourceManager.GetString("germanUnityDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Friday.
        /// </summary>
        internal static string goodFriday {
            get {
                return ResourceManager.GetString("goodFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Women&apos;s Day.
        /// </summary>
        internal static string internationalWomensDay {
            get {
                return ResourceManager.GetString("internationalWomensDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labor day.
        /// </summary>
        internal static string laborDay {
            get {
                return ResourceManager.GetString("laborDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luther Reformation Day.
        /// </summary>
        internal static string lutherRefomationDay {
            get {
                return ResourceManager.GetString("lutherRefomationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maundy Thursday.
        /// </summary>
        internal static string maundyThursday {
            get {
                return ResourceManager.GetString("maundyThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s Eve.
        /// </summary>
        internal static string newyear {
            get {
                return ResourceManager.GetString("newyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentecost Sunday.
        /// </summary>
        internal static string pentecostSunday {
            get {
                return ResourceManager.GetString("pentecostSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whit Monday.
        /// </summary>
        internal static string whitMonday {
            get {
                return ResourceManager.GetString("whitMonday", resourceCulture);
            }
        }
    }
}
