//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mitoSoft.Holidays.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mitoSoft.Holidays.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all saints.
        /// </summary>
        internal static string allSaints {
            get {
                return ResourceManager.GetString("allSaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascension of christ.
        /// </summary>
        internal static string ascensionOfChrist {
            get {
                return ResourceManager.GetString("ascensionOfChrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assumption day.
        /// </summary>
        internal static string assumptionDay {
            get {
                return ResourceManager.GetString("assumptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to christmas eve.
        /// </summary>
        internal static string christmasEve {
            get {
                return ResourceManager.GetString("christmasEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corpus christi.
        /// </summary>
        internal static string corpusChristi {
            get {
                return ResourceManager.GetString("corpusChristi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easter sunday.
        /// </summary>
        internal static string easter {
            get {
                return ResourceManager.GetString("easter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easter monday.
        /// </summary>
        internal static string easterMonday {
            get {
                return ResourceManager.GetString("easterMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first christmas day.
        /// </summary>
        internal static string firstChristmas {
            get {
                return ResourceManager.GetString("firstChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good friday.
        /// </summary>
        internal static string goodFriday {
            get {
                return ResourceManager.GetString("goodFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to holy kings.
        /// </summary>
        internal static string holyKings {
            get {
                return ResourceManager.GetString("holyKings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labor day.
        /// </summary>
        internal static string laborDay {
            get {
                return ResourceManager.GetString("laborDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maundythursday.
        /// </summary>
        internal static string maundyThursday {
            get {
                return ResourceManager.GetString("maundyThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new year&apos;s eve.
        /// </summary>
        internal static string newyear {
            get {
                return ResourceManager.GetString("newyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pentecost sunday.
        /// </summary>
        internal static string pentecostSunday {
            get {
                return ResourceManager.GetString("pentecostSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refomation day.
        /// </summary>
        internal static string refomationDay {
            get {
                return ResourceManager.GetString("refomationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second christmas day.
        /// </summary>
        internal static string secondChristmas {
            get {
                return ResourceManager.GetString("secondChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unity day.
        /// </summary>
        internal static string unityDay {
            get {
                return ResourceManager.GetString("unityDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whit monday.
        /// </summary>
        internal static string whitMonday {
            get {
                return ResourceManager.GetString("whitMonday", resourceCulture);
            }
        }
    }
}
